export const en = [
        {
            "ques": "What is Credit Score?",
            "ans": ["Credit score is a 3-digit number, usually between 300 and 900. It represents the creditworthiness of an individual that lenders evaluate when he/she applies for any kind of a credit product like a loan or a credit card. In simpler terms, credit score signifies the trustworthiness of a borrower to pay off the loan in timely manner, without defaults or delay."]
        },
        {
            "ques": "How do I get my Credit Report corrected in case of an error?",
            "ans": [
                 "If you notice an error on your credit reports, it’s crucial to take immediate steps. Some common errors that you might encounter in your Credit Report are:",
                 "- Already closed/settled loan or credit card accounts showing active in the report",
                 "- Incorrect/not relevant loan or credit card accounts details showing in the report",
                 "- Incorrect credit enquiries in the report ",
                 "- Dispute that has been already raised with the bureaus (CIBIL, Experian, Equifax or Highmark) and not resolved",
                 "Your credit data is generated by the respective bureaus and we simply show what is provided to us. However, we strongly recommend that you reach out to the respective bureau on the below mentioned contacts to get the errors corrected",
                 "For CIBIL, go the given link and submit an online dispute: ",
                 "For other bureaus, reach out to them on their respective email addresses as given below:",
                 "Experian -  ",
                 "Equifax - ",
                 "Highmark - ",
                 "Quick Tip: Remember to keep necessary details like report number, credit account number, bank name, etc handy! ",
                 "In case you've already raised a dispute with the respective bureau and it has been more than 90 days, then you can write to us at",
                 " and we would be happy to help!"
             ]
        },
        {
            "ques": "How do I improve my score?",
            "ans": [ 
                "The key to building and maintaining a good credit history is to use credit responsibly. Being consistently responsible in the way you handle credit can push your score in the right direction, and to do so you should take the following steps:",
                "-Pay credit card balance in full",
                "-Make timely payments for your loans and credit card",
                "-Keep a tab on your credit card usage",
                "-Borrow more only if you are capable of paying back on time",
                "-Avoid applying/enquiring for multiple credit products (loans/Credit cards)",
                "-Maintain a good credit mix",
                "-Avoid closing your old credit accounts",
                "-Check your credit report regularly to reduce chances of errors",
                "For more tips on how to improve your CIBIL score, please read ",
                "“Establishing a Strong Credit Score: 9 Tips and Tricks.”"
            ]
        },
        {
            "ques": "Why can't I see my score?",
            "ans": [
               "Possible reasons why your report could not be generated are:",
               "1. No credit history: Credit scoring models cannot generate a score without past credit information.",
               "2. Insufficient credit history: If you have a very recent credit history (less than six months), you probably will not have a credit score.",
               "3. Incorrect information: When applying for your credit report, the information you gave did not match with the credit bureau due to which your identity could not be authenticated by our bureau partner. To get past this situation, you can reach out to the respective Bureau on the below mentioned contacts to get the information corrected",
               "For CIBIL, go the given link and submit an online dispute: ",
               "For other bureaus, reach out to them on their respective email addresses as given below:",
               "Experian -  ",
               "Equifax - ",
               "Highmark - "
            ]
        },
        {
            "ques": "Why hasn't my score been refreshed?",
            "ans": [
                "The credit score is refreshed based on the new information that is available to the bureau. This information is shared on a monthly basis with the bureau. Subsequently, any change in the score may take at least a month to show.",
                "Besides, even in cases where new information has been provided it is possible that the new score is the same as the last one. This can be identified by comparing the reports of two months.",
                "In case the information isn’t updated even after more than a month, the customer should immediately contact the concerned bureau and raise a query.",
                "For CIBIL, go the given link and submit an online dispute: ",
                "For other bureaus, reach out to them on their respective email addresses as given below:",
                "Experian -  ",
                "Equifax - ",
                "Highmark - "
               ]
        },
        {
            "ques": "How can I change my personal details like name, email address & phone number?",
            "ans": [
                 "Some of the information on your profile like email address & employer details can be changed instantly.",
                 "1. From your credit report dashboard, click the menu button on the top left.",
                 "2. In the menu, click 'My Profile' and change your email address and employer details.",
                 "Other personal details like name, date of birth, phone number, PAN card & more can be updated by reaching out to the respected bureau here if you wish to change this in your report.",
                 "For CIBIL, go the given link and submit an online dispute: ",
                 "For other bureaus, reach out to them on their respective email addresses as given below:",
                 "Experian -  ",
                 "Equifax - ",
                 "Highmark - ",
                "Quick Tip: Remember to keep necessary details like report number, credit account number, bank name, etc handy!"
            ]
        },
        {
            "ques": "Why is your Credit Health Important?",
            "ans": [
                "Each time you apply for a credit product (any kind of loan or a credit card), the lender bank or financial institution first checks your creditworthiness - By looking at your Credit Score. Through your Credit Score, lenders try to gauge whether you would repay the loan EMIs or credit card dues responsibly, if they approve your application for loan or credit card.",
                "Your Credit Score ranges between 300 and 900 (the higher the better) and is based on your track-record with credit. This score is determined by how well you have behaved with credit in the past i.e. if you have paid your EMIs and credit card bills on time, how much debt you have taken, what is your existing debt, are you too reliant on credit, how long have you been using credit etc.",
                "A high credit score means you are credit healthy and banks and other lenders should be happy to provide you with a loan or credit card. A high credit score will also help you get credit at the lowest interest rates. A low score, on the other hand, poses a risk for lenders and hence, you would struggle to get a credit product from them."
            ]
        },
        {
            "ques": "How is your Credit Score calculated?",
            "ans": ["Every month, all lending institutions in India submit repayment performance of their borrowers to credit bureaus, which calculate the credit score of each borrower.  In India, there are 4 credit bureaus, each has its own credit scoring model. Hence, your credit score, though between 300 and 900, would vary from one bureau to another."]
        },
        {
            "ques": "What's in this Credit Health Report?",
            "ans": ["Paisabazaar.com's Credit Health report dives into your credit behaviour and provides you with a succinct performance analysis on each of the factors that determine your credit score. It’s jargon-free, easy to understand and would clearly tell you where you are doing well and areas where you need to improve."]
        },
        {
            "ques": "What is 30-Day Free trial of CHR?",
            "ans":  ["Credit Health report shall be made available to everyone without any cost for thirty days. You have to register a mandate to opt for the free trial so as to let us deduct the monthly charges from your preferred mode of payment post the free trial ends."]
        },
        {
            "ques": "How much amount will be deducted from my account at the end of the free trial?",
            "ans": ["CHR charges will be deducted monthly from your registered mode of payment @ Rs. 99 /- month."]
        },
        {
            "ques": "How does Cancel anytime work?",
            "ans": ["Users can cancel their subscription anytime from the Paisabazaar website itself. If you cancel within the free trial period, your mandate gets cancelled and there won’t be any deduction from your account. If you cancel after the free trial period, there won’t be any new deduction from your account and your services shall continue until the end of that month’s billing period."]
            
        } 
];