import React, { } from 'react';
import CoreModal            from 'pages/coreUI/coreModal/CoreModal';
import Button               from 'pages/coreUI/common/_button';
import './styles/WhereYourCreditScoreStandsModal.scss';


const propTypes     = {};

function WhereYourCreditScoreStandsModal (props){
    const {score, activeBureau,actionHandler, }  = props;
   
    const scoreBand = score && score.scoreBand ? score.scoreBand.toLowerCase() : '';    
   
    return (
            <CoreModal
                isOpenModal       = {props.isScoreStandsModal}
                customIdName      = {'WhereYourCreditScoreStandsModal'}
                customClassName   = {'WhereYourCreditScoreStandsModal fixedModal'}
                callBackAction    = {() => actionHandler('closeModal',false)}
                modalHeading      = {""}
                disableBodyScroll = {true}
                closeCW           = {true}
                modalBody         = {                 
                    <div className={`${scoreBand} WhereYourCreditScoreStandsModal`}>
                        <h3 className='title'>Where Your Credit Score Stands</h3>
                        <div className='scoreDetails'>
                            <div className='score'>
                                <h4 className='scoreName'>Your <img  height="auto" width="auto" src={`/images/icons/bureau/${activeBureau.toLowerCase()}.svg`} alt="bureau"/> Score is </h4>
                                <p className={`scoreBand`}>{score.score} / <span className={`${scoreBand}`}>{scoreBand}</span></p> 
                            </div>
                            <div className="separator" />
                            <div className='scoreInfo'>
                                <div className='_item'>
                                    <h4 className='_title'>Higher than 81% of users in Delhi</h4>
                                    <div className={`progress active`} ></div>
                                </div>
                                <div className='_item'>
                                    <h4 className='_title'>Higher than 89% of users in India</h4>
                                    <div className={`progress active`} ></div>
                                </div>
                            </div>
                        </div>                        
                        <p className='infoText'>See how your score stacks up against other Paisabazaar customers in your state. We're calculating the average of the scores in the last 3 months. Credit scores are generated by the CIBIL Credit Bureau. </p>
                        <div className='buttonContainer'>
                            <Button
                                className="btn scoreFactorsBtn"
                                btnClickHandler={() => actionHandler('factors', {})}
                                buttonText={'Know more about your accounts'}
                                btnRightIcon
                                btnRightIconSrc={'/images/icons/rightAngleArrow.svg'}
                            />
                        </div>
                    </div>
                }
            />
        );
}

WhereYourCreditScoreStandsModal.propTypes = propTypes;


export default WhereYourCreditScoreStandsModal;
